# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from package.ui.Browse_QPushButton import Browse_QPushButton
from package.WebContentScraper import WebContentScraper
from package.ui.Worker import Worker
import os
import sys


class Ui_BaseWidget(object):
    @staticmethod
    def runUi():
        app = QtWidgets.QApplication(sys.argv)
        BaseWidget = QtWidgets.QWidget()
        ui = Ui_BaseWidget()
        ui.setupUi(BaseWidget)
        BaseWidget.show()
        sys.exit(app.exec())
    def setupUi(self, BaseWidget):
        BaseWidget.setObjectName("BaseWidget")
        BaseWidget.resize(726, 329)
        BaseWidget.setStyleSheet("")
        self.searchingGroupbox = QtWidgets.QGroupBox(parent=BaseWidget)
        self.searchingGroupbox.setGeometry(QtCore.QRect(20, 10, 681, 121))
        self.searchingGroupbox.setObjectName("searchingGroupbox")
        self.label = QtWidgets.QLabel(parent=self.searchingGroupbox)
        self.label.setGeometry(QtCore.QRect(30, 30, 81, 19))
        self.label.setObjectName("label")
        self.keywordInput = QtWidgets.QLineEdit(parent=self.searchingGroupbox)
        self.keywordInput.setGeometry(QtCore.QRect(120, 30, 531, 25))
        self.keywordInput.setObjectName("keywordInput")
        self.label_2 = QtWidgets.QLabel(parent=self.searchingGroupbox)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 81, 19))
        self.label_2.setObjectName("label_2")
        self.locationComboBox = QtWidgets.QComboBox(parent=self.searchingGroupbox)
        self.locationComboBox.setGeometry(QtCore.QRect(120, 70, 141, 25))
        self.locationComboBox.setObjectName("locationComboBox")
        self.locationComboBox.addItems(["Tai Wan","Hong Kong"])
        self.locationComboBox.setCurrentIndex(0)

        self.groupBox_2 = QtWidgets.QGroupBox(parent=BaseWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 140, 681, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 61, 19))
        self.label_3.setObjectName("label_3")
        self.savePathInput = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.savePathInput.setGeometry(QtCore.QRect(110, 30, 441, 25))
        self.savePathInput.setObjectName("savePathInput")
        self.savePathInput.setText(os.path.dirname(os.path.realpath(sys.argv[0])))

        self.browseButton = Browse_QPushButton(parent=self.groupBox_2,connection_unit_obj=self.savePathInput,file_format_filter="None")
        self.browseButton.setGeometry(QtCore.QRect(560, 30, 93, 28))
        self.browseButton.setObjectName("browseButton")
        self.browseButton.clicked.connect(self.browseButton.connect_open_folder)

        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 73, 81, 19))
        self.label_4.setObjectName("label_4")
        self.FormatComboBox = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.FormatComboBox.setGeometry(QtCore.QRect(110, 70, 141, 25))
        self.FormatComboBox.setObjectName("FormatComboBox")
        self.FormatComboBox.addItems([".csv",".pdf"])
        self.FormatComboBox.setCurrentIndex(0)
        self.startButton = QtWidgets.QPushButton(parent=BaseWidget)
        self.startButton.setGeometry(QtCore.QRect(610, 280, 93, 28))
        self.startButton.setObjectName("startButton")
        self.startButton.clicked.connect(self.startClickedEvent)
        self.stateLabel = QtWidgets.QLabel(parent=BaseWidget)
        self.stateLabel.setGeometry(QtCore.QRect(500, 285, 100, 19))
        self.stateLabel.setObjectName("stateLabel")
        self.resultNeedInput = QtWidgets.QLineEdit(parent=self.searchingGroupbox)
        self.resultNeedInput.setGeometry(QtCore.QRect(490, 70, 61, 25))
        self.resultNeedInput.setObjectName("ResultNeed")
        self.resultNeedInput.setText("0")
        self.resultNeedInput.textChanged.connect(self.resultNeedInputEvent)

        self.label_5 = QtWidgets.QLabel(parent=self.searchingGroupbox)
        self.label_5.setGeometry(QtCore.QRect(310, 73, 181, 19))
        self.label_5.setObjectName("label_5")

        self.stateLabel.setText("READY!")
        self.retranslateUi(BaseWidget)
        QtCore.QMetaObject.connectSlotsByName(BaseWidget)

    def retranslateUi(self, BaseWidget):
        _translate = QtCore.QCoreApplication.translate
        BaseWidget.setWindowTitle(_translate("Searching", "Searching"))
        self.searchingGroupbox.setTitle(_translate("BaseWidget", "Searching"))
        self.label.setText(_translate("BaseWidget", "Keyword:"))
        self.label_2.setText(_translate("BaseWidget", "Location:"))
        self.groupBox_2.setTitle(_translate("BaseWidget", "Output"))
        self.label_3.setText(_translate("BaseWidget", "Save to: "))
        self.browseButton.setText(_translate("BaseWidget", "Browse"))
        self.label_4.setText(_translate("BaseWidget", "Format:"))
        self.startButton.setText(_translate("BaseWidget", "Start"))
        self.label_5.setText(_translate("BaseWidget", "Searching Result Need:"))

    def startClickedEvent(self):

        self.startButton.setDisabled(True)
        self.stateLabel.setText("WORKING...")
        if self.keywordInput.text() == "" or int(self.resultNeedInput.text()) == 0:
            self.startButton.setDisabled(False)
            self.stateLabel.setText("READY!")
            return

        location = "TW"
        if self.locationComboBox.currentText() == "Hong Kong":
            location = "HK"


        webScraper = WebContentScraper(
            keyword=self.keywordInput.text(),
            location=location,
            savefilePath=self.savePathInput.text(),
            resultNeed=int(self.resultNeedInput.text())
        )

        # webScraper.startSearch(self.FormatComboBox.currentText())
        self.worker = Worker(webScraper,self.FormatComboBox.currentText())
        # self.worker.finished.connect(self.onSearchFinished)
        self.worker.returnResult.connect(self.onSearchFinished)
        self.worker.start()


    def onSearchFinished(self,result):
        if result == "error":
            self.stateLabel.setText("Connect Error !")
            self.startButton.setDisabled(False)
            return

        self.stateLabel.setText("READY!")
        self.startButton.setDisabled(False)

    def resultNeedInputEvent(self):
        text = self.resultNeedInput.text()

        try:
            num = int(text)
            if num >= 0:
                self.resultNeedInput.setText(text)
            else:
                self.resultNeedInput.setText("0")
        except Exception as e:
            self.resultNeedInput.setText("0")



if __name__ == "__main__":
    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # BaseWidget = QtWidgets.QWidget()
    # ui = Ui_BaseWidget()
    # ui.setupUi(BaseWidget)
    # BaseWidget.show()
    # sys.exit(app.exec())
    Ui_BaseWidget.runUi()
